0urFit/OurFit_client

- next.config.js
- src/common/molecules/BottomBar.tsx
- src/common/molecules/InfoInput.tsx
- src/common/molecules/LoginInput.tsx
- src/common/molecules/SubmitButton.tsx
- src/common/molecules/style.ts
- src/pages/_document.tsx
-common/moleculs 코드리뷰 후 코드 수정, Styled-Components FOUC 에러 수정
> common/moleculs 코드리뷰 후 코드 수정, Styled-Components FOUC 에러 수정

- src/common/molecules/PostCard.tsx
- src/common/molecules/style.ts
> @tjswo2292/molecules

- src/pages/index.tsx
- src/pages/login.tsx
- chore: 파일 수정
<br>
- pages/index.tsx을 초기 page로 사용하기 위해 login.tsx를 대체
<br>
> chore: 파일 수정

- src/apis/auth.ts
- src/apis/client.ts
- src/common/molecules/SubmitButton.tsx
- src/components/signup/index.tsx
> feat: LocalNickname API 추가

- src/components/login/index.tsx
- src/pages/_app.tsx
- src/pages/api/auth/[...nextauth].ts
> chore: kakao login

- src/components/login/index.tsx
- src/components/login/type.ts
- 비회원 처리
- 비회원일 때, error message 추가
- type 정의
> feat : 비회원 처리

- src/common/layout/style.ts
- src/common/molecules/style.ts
- src/components/save/style.ts
- src/pages/mypage/likes/index.tsx
- src/pages/mypage/posts/index.tsx
- design: defaultLayout, getLayout 수정
- design: defaultLayout overflow 삭제
<br>
- design: defaultLayout, getLayout 수정
- design: defaultLayout overflow 삭제
<br>
> design: defaultLayout, getLayout 수정

- src/components/signup/index.tsx
- src/components/signup/kakao/index.tsx
- fix: signup api 에러 핸들링 수정
<br>
- fix: signup api 에러 핸들링 수정
<br>
> fix: signup api 에러 핸들링 수정

- package-lock.json
- package.json
- #47 
- redux-toolkit delete, redux Install
> chore: redux-toolkit delete, redux Install

- package-lock.json
- package.json
- src/pages/_app.tsx
- src/store/hook.ts
- src/store/slices/authSlice.ts
- src/store/store.ts
#49 
- 인증/인가에 필요한 package 추가
- store 생성
- 인증/인가에 필요한 package 추가
- store 생성
> RTK, react-cookie package 추가 및 store 생성

- src/apis/client.ts
- src/components/loading/index.tsx
- src/pages/home/index.tsx
- src/pages/verifying/index.tsx
- src/utils/manageCookie.ts
- refresh token을 사용하여 access token이 만료되었을 때 갱신
> feat: access token 갱신

- src/pages/_app.tsx
- src/store/slices/authSlice.ts
- src/store/store.ts
- redux toolkit slice, store 설정변경
<br>
> feat: redux toolkit slice, store 설정변경

- src/apis/auth.ts
- src/apis/client.ts
- src/components/home/index.tsx
- src/components/login/index.tsx
- src/components/login/type.ts
> fix: 소셜로그인 에러 수정

- src/components/loading/index.tsx
- src/components/login/index.tsx
- src/pages/verifying/index.tsx
- src/store/slices/authSlice.ts
- src/store/slices/userSlice.ts
- src/store/store.ts
- kakao 로그인시 store에 email, gender 저장
<br>
> kakao 로그인시 store에 email, gender 저장

- src/common/molecules/style.ts
- homepage image 오류 수정
- routine image가 페이지를 덮는 현상 수정
> fix: homepage image 오류 수정

- src/components/home/index.tsx
- /home 경로에서 운동루틴 api 요청하는 로직이 중복됨
- 기존 코드에서 중복되는 로직 제거
> homepage api 중복요청 수정

- src/utils/getErrorMessage.ts
- Error 처리 util 함수 추가
- Error 종류별로 Error를 처리하기 위한 함수
> feat: Error 처리 util 함수 추가

- src/common/molecules/CreateButton.tsx
- src/common/molecules/style.ts
#81 
- design: CreateButton Component 동적 스타일링
- chore: CreateButton path 조건 수정
<br>
- design: CreateButton Component 동적 스타일링
- chore: CreateButton path 조건 수정
<br>
> design: CreateButton Component 동적 스타일링

- src/components/loading/type.ts
- src/pages/verifying/index.tsx
- "취소" 버튼 클릭시에 Server Side에서 Client Side로 message 전달
- "취소" 버튼 클릭시에 쿼리스트링으로 "error_description" 메시지가 전달된다. 이 메시지가 있을 시에 "/" 경로로 redirect 시켜준다.
> KakaoLogin시 "취소

- src/common/molecules/style.ts
> RoutineCard style 수정

- src/apis/auth.ts
- src/common/molecules/LikeControl.tsx
- src/common/molecules/RoutineCard.tsx
- src/common/molecules/style.ts
- src/components/home/index.tsx
- src/components/home/style.ts
- src/pages/home/detail/[slug].tsx
- src/utils/deleteBlank.ts
- 공통적으로 사용 되는 좋아요 컴포넌트 분리
- dynamic routing 추가
- 로고 디자인 속성 수정
- 미완성이지만 팀원도 RoutineCard 컴포넌트를 사용해야 하기 떄문에 PR을 날림
> 공통적으로 사용 되는 좋아요 컴포넌트 분리

- src/common/molecules/style.ts
- src/components/home/style.ts
- LikeIconBtn width, height 변경
- homeDetail 페이지 FooterBox 정렬 수정
- LikeIconBtn : 25px -> 30px
> [design] LikeIconBtn width, height 변경 및 homeDetail 페이지 FooterBox 정렬 수정

- src/apis/auth.ts
- src/common/molecules/CreateButton.tsx
- src/components/save/detail/index.tsx
- src/components/save/index.tsx
#94 
- feat: CreateButton Component onClick 함수 props로 전달
<br>
- feat: CreateButton Component onClick 함수 props로 전달
<br>
> feat: CreateButton Component onClick 함수 props로 전달

- src/apis/auth.ts
- src/apis/client.ts
- src/common/molecules/LikeControl.tsx
- src/common/molecules/RoutineCard.tsx
- src/components/home/detail/index.tsx
- src/components/home/style.ts
- src/hooks/useAddOptions.tsx
- 브랜치 재구성을 위한 PR
- 프로젝트를 진행하면서 기능개발에만 치중한 나머지 git blanch 관리를 하지 않아서 branch를 재설정 하려고 현재 작업중인 결과물들을 Pull request후 merge할 예정이다.
> 브랜치 재설정 위한 PR

- src/common/layout/style.ts
- src/common/molecules/style.ts
- src/components/home/index.tsx
- src/components/home/style.ts
- src/components/login/style.ts
- src/components/save/style.ts
- 반응형 디자인 추가
- 갤럭시 기기에서 디자인이 깨지는 현상 발생하여 반응형 디자인 수정
> 반응형 디자인 수정

- src/common/layout/style.ts
- src/common/molecules/RoutineCard.tsx
- src/components/home/ExerciseDetail.tsx
- src/components/home/RoutineDetail.tsx
- src/components/home/detail/index.tsx
- src/components/home/style.ts
- src/components/home/type.ts
- src/hooks/useAddOptions.tsx
- src/store/slices/periodSlice.ts
- src/store/store.ts
> homedetail Page 완성

- src/apis/auth.ts
- src/common/molecules/RoutineCard.tsx
- src/common/molecules/type.ts
- src/components/save/detail/Pagination.tsx
- src/components/save/detail/index.tsx
- src/components/save/index.tsx
- src/components/save/style.ts
- src/components/save/type.ts
#105 
- chore: routine weekProgress(주차) 추가
- feat: save/detail 페이지 pagination 기능 추가
- feat: routineSuccess api 추가
<br>
- chore: routine weekProgress(주차) 추가
- feat: save/detail 페이지 pagination 기능 추가
- feat: routineSuccess api 추가
<br>
> saveDetail Page 완성

- src/pages/signup/index.tsx
- src/pages/signup/kakao/index.tsx
- chore: signup page 재생성
<br>
- chore: signup page 재생성
<br>
> chore: signup page 재생성

- src/components/login/index.tsx
> fix: email input bug

- src/common/molecules/RoutineCard.tsx
- src/common/molecules/style.ts
- src/common/molecules/type.ts
- routineCard backgroundColor, disabled 추가
- common/RoutineCard 컴포넌트 클릭 시에 background "#e1e2e3" 변경 및 disabled 속성 추가
> feat: routineCard backgroundColor, disabled 추가

- src/apis/auth.ts
- src/common/molecules/RoutineCard.tsx
- src/common/molecules/style.ts
- src/components/save/index.tsx
-  save routine "삭제" 버튼 추가
-  save routine "삭제" 버튼 추가
> feat: save routine "삭제" 버튼 추가

- src/components/home/style.ts
- homedetail footerbox responsive 수정
> homedetail footerbox responsive 수정

- src/common/molecules/LikeControl.tsx
- 변수명, import 순서 수정
- test 해보기 위해 사용했던 변수명을 그대로 pr 날려서 이 부분 ### 수정
> refactor: 변수명, import 순서 수정

- src/data/SignInData.ts
- build error
- SignInData의 inputValue 철자오류
> bug: build error

- src/components/mypage/index.tsx
- mypage profile description
- 사용자가 회원가입할 때, 입력하지 않은 정보를 '-'으로 보여줄 수 있게 추가
> feat: 사용자가 입력한 값이 없을 때 '-' 보여주기

- src/apis/auth.ts
- MainSave endpoint 변경
- api.ts에 정의되어있는 MainSave api endpoint 변경
> bug: MainSave endpoint 변경

- src/apis/auth.ts
- src/apis/client.ts
> redirect uri 수정

- src/apis/client.ts
- aws amplify에서 제공하는 도메인으로 변경
-
> aws amplify에서 제공하는 도메인으로 변경

- src/apis/auth.ts
- src/components/home/detail/index.tsx
- src/components/home/style.ts
- src/components/home/type.ts
> /home/detail 운동 제목 추가

- src/pages/verifying/index.tsx
- kakao api 성공 응답 스키마 변경
token -> accessToken
> style: change kakao login api 응답 스키마

- src/pages/404.tsx
- 404 커스텀 에러 import 경로명 수정
- ClientErrorMessage -> clientErrorMessage
> style: 404 커스텀 에러 import 경로명 수정

- src/apis/auth.ts
- src/common/layout/style.ts
- src/common/molecules/CreateButton.tsx
- src/common/molecules/InfoInput.tsx
- src/common/molecules/RoutineCard.tsx
- src/common/molecules/style.ts
- src/components/home/style.ts
- src/components/login/style.ts
- src/components/mypage/style.ts
- src/components/save/detail/ExerciseDetailMain.tsx
- src/components/save/style.ts
- src/components/signup/SelectBox.tsx
- src/components/signup/style.ts
- 반응형 스타일 수정 & api path 변경
- px -> rem
- nickname, email api path 변경
- 반응형 디자인 수정
> 반응형 스타일 수정 & api path 변경

- src/common/molecules/CreateButton.tsx
> 공통 컴포넌트 불필요한 style 코드 삭제

- src/pages/index.tsx
- src/utils/constants.ts
- src/utils/manageCookie.ts
- src/utils/manageLocalStorage.ts
- 로그인 상태일 때, '/' 경로 접근 막기
- '/' 경로에서  serverSideProps 사용하여 refresh token 있을시에 /home 경로로 redirect 시킴
> 로그인 상태일 때, '/' 경로 접근 막기

- src/apis/auth.ts
- src/common/molecules/CreateButton.tsx
- src/common/molecules/style.ts
- src/common/molecules/type.ts
- src/components/home/detail/index.tsx
- homedetail 페이지 등록된 운동 루틴은 "등록하기" 버튼 색 변경 및 사용하기 못하게
- CreateButton 공통 컴포넌트 동적 스타일링 추가
- routineId로 등록 유무 조회하는 api 추가
> homedetail 페이지 등록된 운동 루틴은 "등록하기" 버튼 색 변경 및 사용하기 못하게

- src/common/molecules/BottomBar.tsx
- src/components/home/index.tsx
- src/components/home/style.ts
- src/components/save/index.tsx
- 모바일 화면일 때, BottomBar 가려지는 현상
- 모바일 화면에서 스크롤시 BottomBar가 가려지는 현상이 발생한다. BottomBar에 Wrapper를 씌우고 position:fixed
> 모바일 화면일 때, BottomBar 가려지는 현상

- src/common/layout/style.ts
- src/components/mypage/style.ts
> design: 반응형수정

- src/common/layout/AuthLayout.tsx
- src/common/layout/DefaultLayout.tsx
- src/common/layout/style.ts
- src/common/molecules/BottomBar.tsx
- src/common/molecules/style.ts
- src/common/molecules/type.ts
- src/components/home/index.tsx
- src/components/home/style.ts
- src/components/mypage/index.tsx
- src/components/mypage/style.ts
- src/components/posts/index.tsx
- src/components/save/detail/ExerciseDetailMain.tsx
- src/components/save/index.tsx
- src/components/save/style.ts
- src/components/signup/kakao/index.tsx
- src/components/signup/style.ts
- src/pages/_app.tsx
- src/pages/home/detail/[slug].tsx
- src/pages/home/index.tsx
- src/pages/index.tsx
- src/pages/mypage/index.tsx
- src/pages/mypage/likes/index.tsx
- src/pages/posts/index.tsx
- src/pages/save/detail/[slug].tsx
- src/pages/save/index.tsx
- src/pages/signup/index.tsx
- src/pages/signup/kakao/index.tsx
- src/styles/GlobalStyle.tsx
> Layout 수정, 추가

- src/apis/likeRequest.ts
- src/common/molecules/LikeControl.tsx
- src/common/molecules/RoutineCard.tsx
- src/components/home/detail/index.tsx
- src/pages/home/detail/[slug].tsx
- LikeControl 컴포넌트 Refactoring
기존
- LikeControl 컴포넌트 내부에서 초깃값을 false로 지정하여 사용
Refactoring 후
- LikeControl에 props로 초깃값 전달
> LikeControl 컴포넌트 Refactoring

- src/components/loading/index.tsx
- src/pages/_app.tsx
- src/pages/verifying/index.tsx
- src/store/Providers.tsx
- src/store/slices/authSlice.ts
- src/store/slices/periodSlice.ts
- src/store/slices/routineSlice.ts
- src/store/slices/userSlice.ts
- src/store/store.ts
Redux toolkit legacy 코드 업데이트, 카카오 회원가입 후 '/' 경로로 이동 안되는 버그
> Redux toolkit legacy 코드 업데이트, 카카오 회원가입 후 '/' 경로로 이동 안되는 버그

- package-lock.json
- package.json
- src/apis/apiService.ts
- src/apis/type.ts
- src/common/molecules/Loading.tsx
- src/common/molecules/style.ts
- src/components/home/index.tsx
- src/pages/_app.tsx
- Home 컴포넌트 데이터 패칭 react-query로 변경
useEffect hook으로 데이터 패칭 -> react-query로 변경
> Home 컴포넌트 데이터 패칭 react-query로 변경, 로딩 컴포넌트 추가
